# Generated by Django 4.2.4 on 2023-08-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
