# Generated by Django 4.2.4 on 2023-08-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartmodel_cart_id_alter_cartmodel_cart_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
