# Generated by Django 4.2.4 on 2023-08-30 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_alter_cartmodel_cart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cartitemmodel',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartmodel'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='cart_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
